[project]
name = "impromptu"
version = "0.1.0"
description = "Automatic, end-to-end circuit prototyping system for small-to-medium sized circuits"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
